// <auto-generated />
using System;
using Leave_Mangement_System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Leave_Mangement_System.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250921103844_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Leave_Mangement_System.Models.Department", b =>
                {
                    b.Property<int>("DeptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeptId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DeptId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DeptId = 1,
                            Name = "Human Resources"
                        },
                        new
                        {
                            DeptId = 2,
                            Name = "Information Technology"
                        },
                        new
                        {
                            DeptId = 3,
                            Name = "Finance"
                        },
                        new
                        {
                            DeptId = 4,
                            Name = "Marketing"
                        },
                        new
                        {
                            DeptId = 5,
                            Name = "Operations"
                        },
                        new
                        {
                            DeptId = 6,
                            Name = "Sales"
                        });
                });

            modelBuilder.Entity("Leave_Mangement_System.Models.Employee", b =>
                {
                    b.Property<int>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpId"));

                    b.Property<int>("DeptId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmailManager")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Hr")
                        .HasColumnType("bit");

                    b.Property<int>("LeaveBalance")
                        .HasColumnType("int");

                    b.Property<bool>("Manager")
                        .HasColumnType("bit");

                    b.Property<string>("ManagerName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameEmployee")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PolicyId")
                        .HasColumnType("int");

                    b.HasKey("EmpId");

                    b.HasIndex("DeptId");

                    b.HasIndex("PolicyId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmpId = 1,
                            DeptId = 1,
                            Email = "ahmed.hassan@company.com",
                            Hr = true,
                            LeaveBalance = 35,
                            Manager = true,
                            NameEmployee = "Ahmed Hassan",
                            PolicyId = 3
                        },
                        new
                        {
                            EmpId = 2,
                            DeptId = 1,
                            Email = "fatma.mohamed@company.com",
                            EmailManager = "ahmed.hassan@company.com",
                            Hr = true,
                            LeaveBalance = 28,
                            Manager = false,
                            ManagerName = "Ahmed Hassan",
                            NameEmployee = "Fatma Mohamed",
                            PolicyId = 2
                        },
                        new
                        {
                            EmpId = 3,
                            DeptId = 2,
                            Email = "omar.ali@company.com",
                            Hr = false,
                            LeaveBalance = 30,
                            Manager = true,
                            NameEmployee = "Omar Ali",
                            PolicyId = 3
                        },
                        new
                        {
                            EmpId = 4,
                            DeptId = 2,
                            Email = "mona.ibrahim@company.com",
                            EmailManager = "omar.ali@company.com",
                            Hr = false,
                            LeaveBalance = 21,
                            Manager = false,
                            ManagerName = "Omar Ali",
                            NameEmployee = "Mona Ibrahim",
                            PolicyId = 1
                        },
                        new
                        {
                            EmpId = 5,
                            DeptId = 2,
                            Email = "khaled.mahmoud@company.com",
                            EmailManager = "omar.ali@company.com",
                            Hr = false,
                            LeaveBalance = 25,
                            Manager = false,
                            ManagerName = "Omar Ali",
                            NameEmployee = "Khaled Mahmoud",
                            PolicyId = 2
                        },
                        new
                        {
                            EmpId = 6,
                            DeptId = 3,
                            Email = "sara.ahmed@company.com",
                            Hr = false,
                            LeaveBalance = 32,
                            Manager = true,
                            NameEmployee = "Sara Ahmed",
                            PolicyId = 3
                        },
                        new
                        {
                            EmpId = 7,
                            DeptId = 3,
                            Email = "mohamed.youssef@company.com",
                            EmailManager = "sara.ahmed@company.com",
                            Hr = false,
                            LeaveBalance = 18,
                            Manager = false,
                            ManagerName = "Sara Ahmed",
                            NameEmployee = "Mohamed Youssef",
                            PolicyId = 1
                        },
                        new
                        {
                            EmpId = 8,
                            DeptId = 4,
                            Email = "nour.kamal@company.com",
                            Hr = false,
                            LeaveBalance = 28,
                            Manager = true,
                            NameEmployee = "Nour Kamal",
                            PolicyId = 3
                        },
                        new
                        {
                            EmpId = 9,
                            DeptId = 4,
                            Email = "amr.salah@company.com",
                            EmailManager = "nour.kamal@company.com",
                            Hr = false,
                            LeaveBalance = 22,
                            Manager = false,
                            ManagerName = "Nour Kamal",
                            NameEmployee = "Amr Salah",
                            PolicyId = 1
                        },
                        new
                        {
                            EmpId = 10,
                            DeptId = 5,
                            Email = "heba.mostafa@company.com",
                            Hr = false,
                            LeaveBalance = 35,
                            Manager = true,
                            NameEmployee = "Heba Mostafa",
                            PolicyId = 3
                        },
                        new
                        {
                            EmpId = 11,
                            DeptId = 5,
                            Email = "tamer.rashad@company.com",
                            EmailManager = "heba.mostafa@company.com",
                            Hr = false,
                            LeaveBalance = 19,
                            Manager = false,
                            ManagerName = "Heba Mostafa",
                            NameEmployee = "Tamer Rashad",
                            PolicyId = 1
                        },
                        new
                        {
                            EmpId = 12,
                            DeptId = 6,
                            Email = "yasmin.fouad@company.com",
                            Hr = false,
                            LeaveBalance = 30,
                            Manager = true,
                            NameEmployee = "Yasmin Fouad",
                            PolicyId = 2
                        },
                        new
                        {
                            EmpId = 13,
                            DeptId = 6,
                            Email = "hassan.gamal@company.com",
                            EmailManager = "yasmin.fouad@company.com",
                            Hr = false,
                            LeaveBalance = 15,
                            Manager = false,
                            ManagerName = "Yasmin Fouad",
                            NameEmployee = "Hassan Gamal",
                            PolicyId = 1
                        },
                        new
                        {
                            EmpId = 14,
                            DeptId = 6,
                            Email = "rana.tarek@company.com",
                            EmailManager = "yasmin.fouad@company.com",
                            Hr = false,
                            LeaveBalance = 26,
                            Manager = false,
                            ManagerName = "Yasmin Fouad",
                            NameEmployee = "Rana Tarek",
                            PolicyId = 2
                        });
                });

            modelBuilder.Entity("Leave_Mangement_System.Models.LeavePolicy", b =>
                {
                    b.Property<int>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PolicyId"));

                    b.Property<int>("ExceptionDays")
                        .HasColumnType("int");

                    b.Property<string>("PolicyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RegularDays")
                        .HasColumnType("int");

                    b.HasKey("PolicyId");

                    b.ToTable("LeavePolicies");

                    b.HasData(
                        new
                        {
                            PolicyId = 1,
                            ExceptionDays = 5,
                            PolicyName = "Standard Policy",
                            RegularDays = 21
                        },
                        new
                        {
                            PolicyId = 2,
                            ExceptionDays = 10,
                            PolicyName = "Senior Policy",
                            RegularDays = 30
                        },
                        new
                        {
                            PolicyId = 3,
                            ExceptionDays = 15,
                            PolicyName = "Management Policy",
                            RegularDays = 35
                        },
                        new
                        {
                            PolicyId = 4,
                            ExceptionDays = 20,
                            PolicyName = "Executive Policy",
                            RegularDays = 40
                        });
                });

            modelBuilder.Entity("Leave_Mangement_System.Models.LeaveRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<int>("EmpId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HrApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("ManagerApproved")
                        .HasColumnType("bit");

                    b.Property<int>("NumberOfDays")
                        .HasColumnType("int");

                    b.Property<bool>("Pending")
                        .HasColumnType("bit");

                    b.Property<bool>("Rejected")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("RequestId");

                    b.HasIndex("EmpId");

                    b.ToTable("LeaveRequests");

                    b.HasData(
                        new
                        {
                            RequestId = 1,
                            EmpId = 4,
                            EndDate = new DateTime(2024, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HrApproved = true,
                            ManagerApproved = true,
                            NumberOfDays = 5,
                            Pending = false,
                            Rejected = false,
                            StartDate = new DateTime(2024, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RequestId = 2,
                            EmpId = 7,
                            EndDate = new DateTime(2025, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HrApproved = false,
                            ManagerApproved = true,
                            NumberOfDays = 3,
                            Pending = true,
                            Rejected = false,
                            StartDate = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RequestId = 3,
                            EmpId = 9,
                            EndDate = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HrApproved = false,
                            ManagerApproved = false,
                            NumberOfDays = 10,
                            Pending = false,
                            Rejected = true,
                            StartDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RequestId = 4,
                            EmpId = 11,
                            EndDate = new DateTime(2025, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HrApproved = false,
                            ManagerApproved = false,
                            NumberOfDays = 6,
                            Pending = true,
                            Rejected = false,
                            StartDate = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RequestId = 5,
                            EmpId = 13,
                            EndDate = new DateTime(2025, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HrApproved = true,
                            ManagerApproved = true,
                            NumberOfDays = 3,
                            Pending = false,
                            Rejected = false,
                            StartDate = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RequestId = 6,
                            EmpId = 5,
                            EndDate = new DateTime(2025, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HrApproved = false,
                            ManagerApproved = true,
                            NumberOfDays = 5,
                            Pending = true,
                            Rejected = false,
                            StartDate = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Leave_Mangement_System.Models.Employee", b =>
                {
                    b.HasOne("Leave_Mangement_System.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Leave_Mangement_System.Models.LeavePolicy", "LeavePolicy")
                        .WithMany("Employees")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("LeavePolicy");
                });

            modelBuilder.Entity("Leave_Mangement_System.Models.LeaveRequest", b =>
                {
                    b.HasOne("Leave_Mangement_System.Models.Employee", "Employee")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("EmpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Leave_Mangement_System.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Leave_Mangement_System.Models.Employee", b =>
                {
                    b.Navigation("LeaveRequests");
                });

            modelBuilder.Entity("Leave_Mangement_System.Models.LeavePolicy", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
